- README.md
- src/com/mojang/ld22/Game.java
- src/com/mojang/ld22/InputHandler.java
- src/com/mojang/ld22/entity/Player.java
- src/com/mojang/ld22/level/Level.java
- src/com/mojang/ld22/saveload/Load.java
- src/com/mojang/ld22/saveload/Save.java
- src/com/mojang/ld22/screen/BookAntVenomMenu.java
- src/com/mojang/ld22/screen/BookTestMenu.java
- src/com/mojang/ld22/screen/HomeMenu.java
- src/com/mojang/ld22/screen/LoadingMenu.java
- src/com/mojang/ld22/screen/Menu.java
- src/com/mojang/ld22/screen/ModeMenu.java
- src/com/mojang/ld22/screen/PauseMenu.java
- src/com/mojang/ld22/screen/SleepMenu.java
- src/com/mojang/ld22/screen/StartMenu.java
- src/com/mojang/ld22/screen/TitleMenu.java
- src/com/mojang/ld22/screen/WonMenu.java
- src/com/mojang/ld22/screen/WorldGenMenu.java
- src/com/mojang/ld22/screen/WorldSelectMenu.java
Menus are fixed... to my knowledge, at least.
> Fixmenu merge-back

- src/minicraft/level/LevelGen.java
Added world seeds and fixed the main method so it can be used to generate worlds.
> World seeds and fixed main method.

- src/minicraft/entity/AirWizard.java
- src/minicraft/entity/Arrow.java
- src/minicraft/entity/Bed.java
- src/minicraft/entity/Chest.java
- src/minicraft/entity/Cow.java
- src/minicraft/entity/Crafter.java
- src/minicraft/entity/Creeper.java
- src/minicraft/entity/DeathChest.java
- src/minicraft/entity/DungeonChest.java
- src/minicraft/entity/EnemyMob.java
- src/minicraft/entity/Entity.java
- src/minicraft/entity/Furniture.java
- src/minicraft/entity/Inventory.java
- src/minicraft/entity/ItemEntity.java
- src/minicraft/entity/Knight.java
- src/minicraft/entity/Lantern.java
- src/minicraft/entity/Mob.java
- src/minicraft/entity/MobAi.java
- src/minicraft/entity/PassiveMob.java
- src/minicraft/entity/Pig.java
- src/minicraft/entity/Player.java
- src/minicraft/entity/Sheep.java
- src/minicraft/entity/Skeleton.java
- src/minicraft/entity/Slime.java
- src/minicraft/entity/Snake.java
- src/minicraft/entity/Spark.java
- src/minicraft/entity/Spawner.java
- src/minicraft/entity/Tnt.java
- src/minicraft/entity/Zombie.java
I've added javadoc style comments to most methods (only those which it makes sense to add) in the entity package. I've also added the @Override annotation to the methods which override a method in the parent class.
> Added javadoc to the classes in the entity package

- ideas/ideas for feature updates.txt
- src/minicraft/level/tile/InfiniteFallTile.java
Lets players in creative walk in the sky without clouds, very simple
> Creative player walk in sky

- ideas/ideas for feature updates.txt
- src/minicraft/level/tile/GrassTile.java
grass will now drop seeds more often when hoed as part of going through [ideas for feature updates.txt](https://github.com/chrisj42/minicraft-plus-revived/blob/master/ideas/ideas%20for%20feature%20updates.txt)
> Grass drops more seeds

- src/minicraft/level/tile/FlowerTile.java
Flowers now spread grass at a higher rate than normal grass.
> Made flowers able to spread grass

- src/minicraft/entity/furniture/Tnt.java
- src/minicraft/entity/mob/Creeper.java
creepers and TNT were making HoleTile's when they exploded in the sky level, this fixes that
> Fix holes in sky

- src/minicraft/saveload/LegacyLoad.java
- src/minicraft/saveload/Load.java
Hopefully this fixes it once and for all.
> Fixed the bug with terrain vertically shredding!

- ideas/ideas for feature updates.txt
- ideas/ideas for new additions.txt
removed several ideas that were obviously implemented. Feel free to recommend others that also need removing.
> Cleanup ideas

- ChangeLog.txt
- src/minicraft/core/io/InputHandler.java
- src/minicraft/entity/mob/Player.java
- src/minicraft/screen/BookDisplay.java
- src/minicraft/screen/Menu.java
- src/minicraft/screen/PauseDisplay.java
- src/minicraft/screen/TitleDisplay.java
- src/minicraft/screen/WorldGenDisplay.java
- src/minicraft/screen/entry/ArrayEntry.java
Now you can't press WASD in menus to move the cursor
> No more confusing world naming

- ChangeLog.txt
- src/minicraft/entity/mob/Player.java
- src/minicraft/gfx/Sprite.java
> Mirrored the item sprite in the attack sweep for the up and left directions

- ChangeLog.txt
- src/minicraft/core/Game.java
- src/minicraft/entity/mob/Creeper.java
- src/minicraft/entity/mob/Player.java
- src/minicraft/item/Recipes.java
lots of important stuff that should be fixed right away
> Major bugfixes

- src/minicraft/screen/TitleDisplay.java
Prevented TitleDisplay from picking the birthday splash when returning from another menu
> Splash problems

- src/minicraft/core/Game.java
- src/minicraft/screen/PlayerInvDisplay.java
- src/minicraft/screen/TitleDisplay.java
also added a new debug message at line 51 in the Game class.
> Fixed a sound bug and added a new splash text.

- src/minicraft/entity/Spark.java
- src/minicraft/entity/mob/AirWizard.java
- src/minicraft/level/Level.java
- Do a spark list apart from entity list in Level
- Reduced how many sparks are generated by Air Wizard
- Reduced spark lifetime from 10 seconds to 6 seconds
> Spark optimization

- src/minicraft/entity/furniture/DungeonChest.java
- src/minicraft/level/Level.java
- src/minicraft/saveload/LegacyLoad.java
- src/minicraft/saveload/Load.java
- src/minicraft/saveload/Save.java
Fix dungeon chest and entities to add bugs
> Fix locked dungeon chest when world loads again

- src/minicraft/core/Game.java
- src/minicraft/core/Initializer.java
- src/minicraft/core/Network.java
- src/minicraft/level/Level.java
- src/minicraft/network/MinicraftClient.java
- src/minicraft/network/MinicraftConnection.java
- src/minicraft/network/MinicraftServer.java
Added --port [port] in jar parameters
Added port resolve in multiplayer menu using host:port format
Fixes concurrent exceptions in level class
> Add custom port support and fix some exceptions

- src/minicraft/core/Renderer.java
- src/minicraft/core/World.java
- src/minicraft/level/Level.java
- src/minicraft/saveload/Load.java
- src/minicraft/saveload/Save.java
This will simply save and load a seed in level files to show it in debug info [ F3 ]
If it was a previous world before that 2.0.7-dev2 or if it's an online world it'll show 0 by default
> Save and load the used seed in generating a world

- src/minicraft/entity/mob/AirWizard.java
I don't know if those lines were commented to make a test or something else
If you guys have any problem with the changes you guys can tell me :)
> Removed unnecessary comments in AirWizard.java

- src/main/java/minicraft/gfx/Color.java
- src/main/java/minicraft/item/StackableItem.java
- src/main/java/minicraft/level/tile/CloudCactusTile.java
- src/main/java/minicraft/level/tile/Tiles.java
- src/main/java/minicraft/saveload/Load.java
- src/main/java/minicraft/screen/BookDisplay.java
Fixed Typos and added missing spaces introduced in #189.
> Fixed Typos and added missing spaces.

- src/main/java/minicraft/entity/mob/Player.java
Player now semi-randomly respawns when there is no bed.
i have had my will finally broken and have resorted to using the built in github.com editor
:(
> Random Respawn when without Bed

- src/main/java/minicraft/saveload/Load.java
Fixes issue listed [here](https://github.com/chrisj42/minicraft-plus-revived/issues/217).
It was purely a loading bug.
> Airwizard Loading Level Fix

- src/main/java/minicraft/core/io/Localization.java
> Fixed Localization in IDE

- src/main/java/minicraft/entity/mob/MobAi.java
- src/main/java/minicraft/level/Level.java
> Fixed issue where entity despawned in player's sight

- ChangeLog.txt
- src/main/java/minicraft/level/tile/DirtTile.java
> Fixed stairs rendering in sky

- ChangeLog.txt
- src/main/java/minicraft/screen/WorldGenDisplay.java
Suggested by @TheBigEye in #226.
> Fixes bugs with world seed and adds the ability to use ascii characters

- src/main/java/minicraft/core/Renderer.java
- src/main/java/minicraft/core/io/ConsoleReader.java
- src/main/java/minicraft/core/io/Localization.java
- src/main/java/minicraft/core/io/Settings.java
- src/main/java/minicraft/entity/furniture/Furniture.java
- src/main/java/minicraft/entity/furniture/Spawner.java
- src/main/java/minicraft/entity/mob/RemotePlayer.java
- src/main/java/minicraft/gfx/Color.java
- src/main/java/minicraft/level/Level.java
- src/main/java/minicraft/saveload/LegacyLoad.java
- src/main/java/minicraft/screen/AchievementsDisplay.java
- src/main/java/minicraft/screen/TitleDisplay.java
- Removed a lot of unused imports
- Cleaned up some code that was technically deprecated
> Cleaned up code

- ChangeLog.txt
- src/main/java/minicraft/core/Renderer.java
> Fixed second count for potions

- src/main/java/minicraft/entity/furniture/Tnt.java
- src/main/java/minicraft/entity/mob/AirWizard.java
- src/main/java/minicraft/screen/AchievementsDisplay.java
- src/main/java/minicraft/screen/SkinDisplay.java
Included
+Added Debug for when an Achievement's data is changed (either achieve or unachieve)
+Made "Fashion Show", "Defeat... the air?", "An airy feat!", and "Demolition Demo" all achievable.
> Achievable Achievements Part 1

- src/main/java/minicraft/saveload/Load.java
Fixes #260. Maybe we should write a wrapper class around JSONObject to safely get a value or set it to a default if it doesn't exist?
> Fixed issue with loading difficulty

- ChangeLog.txt
- src/main/java/minicraft/core/io/Localization.java
- src/main/java/minicraft/screen/OptionsMainMenuDisplay.java
- src/main/java/minicraft/screen/ResourcePackDisplay.java
- src/main/java/minicraft/screen/SkinDisplay.java
- src/main/java/minicraft/screen/TexturePackDisplay.java
This closes #249. @Litorom does this look good?
> Changed Texture Packs to Resource Packs

- src/main/java/minicraft/screen/BookDisplay.java
Didn’t test but should work
Closes #285.
> Book Error fix

- src/main/java/minicraft/level/tile/OreTile.java
- src/main/java/minicraft/level/tile/RockTile.java
Fixes #298. Also good background for fixing #176
> Fixed bug where coal dropped from fist and cleaned up OreTile code

- src/main/java/minicraft/screen/AchievementsDisplay.java
- src/main/java/minicraft/screen/SkinDisplay.java
> Add check creative

- src/main/java/minicraft/item/FurnitureItem.java
Resolve the sprite specification problem when the spawner is being picked up.
> Resolve Spawner sprite problem

- src/main/java/minicraft/entity/furniture/Tnt.java
- src/main/java/minicraft/level/tile/ExplodedTile.java
Resolve the negative damages from TNT.
Resolve the second damage with exactly 50 from TNT (ExplodedTile#tick).
> Fix TNT damaging problem

- src/main/java/minicraft/entity/mob/Mob.java
- src/main/java/minicraft/item/PotionType.java
- src/main/java/minicraft/level/Level.java
- src/main/java/minicraft/level/tile/TreeTile.java
- src/main/java/minicraft/screen/KeyInputDisplay.java
- src/main/java/minicraft/screen/PlayerDeathDisplay.java
- src/main/java/minicraft/screen/PlayerInvDisplay.java
Also removed unused imports since those seem to keep crawling into the files somehow.
Old:
New:
Also a small thing to note here is that the order of potion effects changes between saves/loads. Haven't looked into why, nor will I since that is incredibly low priority.
> Changed potion colors to make them visible

- src/main/java/minicraft/core/io/Localization.java
- src/main/java/minicraft/screen/ResourcePackDisplay.java
Fixes the problem with Windows 11 zip style;
resolves the potential compatible problem of localization;
changes to load default textures when no textures detected with the selected pack instead of previous textures.
> Resolve texture pack compatible problem

- src/main/java/minicraft/core/Renderer.java
- src/main/java/minicraft/item/ToolItem.java
> Fix durability rounding problem

- src/main/java/minicraft/core/World.java
- src/main/java/minicraft/level/Level.java
- src/main/java/minicraft/level/LevelGen.java
- src/main/java/minicraft/saveload/Load.java
- src/main/java/minicraft/saveload/Save.java
- src/main/java/minicraft/screen/WorldGenDisplay.java
This pull request resolves the wrong seed implementations.
> Complete Seed Implementation

- src/main/java/minicraft/core/Renderer.java
- src/main/java/minicraft/core/io/InputHandler.java
- src/main/java/minicraft/entity/mob/Player.java
Added keys in order to hide GUI and simplify potion effect display.
> GUI Simplification

- build.gradle
- src/main/java/minicraft/core/Game.java
- src/main/java/minicraft/core/Updater.java
- src/main/java/minicraft/core/io/ControllerHandler.java
- src/main/java/minicraft/core/io/InputHandler.java
- src/main/java/minicraft/entity/mob/Player.java
- src/main/java/minicraft/screen/AchievementsDisplay.java
- src/main/java/minicraft/screen/BookDisplay.java
- src/main/java/minicraft/screen/ContainerDisplay.java
- src/main/java/minicraft/screen/CraftingDisplay.java
- src/main/java/minicraft/screen/Display.java
- src/main/java/minicraft/screen/EndGameDisplay.java
- src/main/java/minicraft/screen/InfoDisplay.java
- src/main/java/minicraft/screen/InventoryMenu.java
- src/main/java/minicraft/screen/KeyInputDisplay.java
- src/main/java/minicraft/screen/Menu.java
- src/main/java/minicraft/screen/MultiplayerDisplay.java
- src/main/java/minicraft/screen/OptionsWorldDisplay.java
- src/main/java/minicraft/screen/PauseDisplay.java
- src/main/java/minicraft/screen/PlayerInvDisplay.java
- src/main/java/minicraft/screen/PopupDisplay.java
- src/main/java/minicraft/screen/QuestsDisplay.java
- src/main/java/minicraft/screen/SkinDisplay.java
- src/main/java/minicraft/screen/TitleDisplay.java
- src/main/java/minicraft/screen/WorldSelectDisplay.java
- src/main/java/minicraft/util/Logging.java
Controller Support:
Current Binds
- A = Attack/Select
- B = Back
- X = Inventory
- Y = Craft
- Menu/Start = Pause
- Joystick/DPad = Movement
- DPad (Menus) = Entry Movement
Tested Controllers:
- Xbox
(Binds may change especially with Quest additions and additional keybinds)
closes #375
> Controller Support

- src/main/java/minicraft/screen/QuestsDisplay.java
Stream.toList() is implemented in java 16, we're targeting java 8. With this PR minicraft will be able to be built again.
> Fix Stream.toList() usage.

- src/main/java/minicraft/core/Initializer.java
- src/main/java/minicraft/core/Renderer.java
- src/main/java/minicraft/core/Updater.java
- src/main/java/minicraft/core/io/ControllerHandler.java
- src/main/java/minicraft/entity/ItemEntity.java
- src/main/java/minicraft/entity/Spark.java
- src/main/java/minicraft/entity/furniture/DungeonChest.java
- src/main/java/minicraft/entity/furniture/Furniture.java
- src/main/java/minicraft/entity/mob/Mob.java
- src/main/java/minicraft/entity/mob/Player.java
- src/main/java/minicraft/level/tile/DecorTile.java
- src/main/java/minicraft/level/tile/MaterialTile.java
- src/main/java/minicraft/level/tile/Tiles.java
- src/main/java/minicraft/network/Network.java
- src/main/java/minicraft/saveload/LegacyLoad.java
- src/main/java/minicraft/saveload/Load.java
- src/main/java/minicraft/saveload/Save.java
- src/main/java/minicraft/screen/BookDisplay.java
- src/main/java/minicraft/screen/Display.java
- src/main/java/minicraft/screen/InventoryMenu.java
- src/main/java/minicraft/screen/MultiplayerDisplay.java
- src/main/java/minicraft/screen/PauseDisplay.java
- src/main/java/minicraft/screen/PlayerInvDisplay.java
- src/main/java/minicraft/screen/QuestsDisplay.java
- src/main/java/minicraft/screen/ResourcePackDisplay.java
- src/main/java/minicraft/screen/entry/LinkEntry.java
- src/main/java/minicraft/screen/entry/RangeEntry.java
Removed unused imports, comment unused variables, add `default: break;` cases for switches missing them, & removed multiplayer data from save & load
> Cleanup unused code.

- src/main/java/minicraft/core/Initializer.java
- src/main/java/minicraft/core/Renderer.java
- src/main/java/minicraft/core/Updater.java
- src/main/java/minicraft/core/io/ControllerHandler.java
- src/main/java/minicraft/entity/ItemEntity.java
- src/main/java/minicraft/entity/Spark.java
- src/main/java/minicraft/entity/furniture/DungeonChest.java
- src/main/java/minicraft/entity/furniture/Furniture.java
- src/main/java/minicraft/entity/mob/Mob.java
- src/main/java/minicraft/entity/mob/Player.java
- src/main/java/minicraft/level/tile/DecorTile.java
- src/main/java/minicraft/level/tile/MaterialTile.java
- src/main/java/minicraft/level/tile/Tiles.java
- src/main/java/minicraft/network/Network.java
- src/main/java/minicraft/saveload/LegacyLoad.java
- src/main/java/minicraft/saveload/Load.java
- src/main/java/minicraft/saveload/Save.java
- src/main/java/minicraft/screen/BookDisplay.java
- src/main/java/minicraft/screen/Display.java
- src/main/java/minicraft/screen/InventoryMenu.java
- src/main/java/minicraft/screen/MultiplayerDisplay.java
- src/main/java/minicraft/screen/PauseDisplay.java
- src/main/java/minicraft/screen/PlayerInvDisplay.java
- src/main/java/minicraft/screen/QuestsDisplay.java
- src/main/java/minicraft/screen/ResourcePackDisplay.java
- src/main/java/minicraft/screen/entry/LinkEntry.java
- src/main/java/minicraft/screen/entry/RangeEntry.java
Reverts MinicraftPlus/minicraft-plus-revived#398
> Revert "Cleanup unused code."

- ChangeLog.md
As the semver format is used instead of the old versioning system, the structure can be described by markdown structure. As some modification can be described more clearly.
> Changes from ChangeLog.txt into markdown format

- ChangeLog.md
- build.gradle
- src/main/java/minicraft/core/Game.java
- src/main/java/minicraft/screen/WorldGenDisplay.java
This is caused by a setting error.
https://discordapp.com/channels/280723930942013440/329379112684879882/1048647785043480697
> Fix a bug on world gen "trouble" popup and add more changelogs

- README.md
*Originally committed as a part of 41ebf97 on #440.*
This adds the instruction for people who are not familiar with GitHub and programing. This provides a guideline for them to download and start the game in general.
> Add game downloading guideline in README

- src/main/java/minicraft/entity/furniture/Crafter.java
- src/main/java/minicraft/entity/furniture/DungeonChest.java
- src/main/java/minicraft/entity/furniture/Furniture.java
- src/main/java/minicraft/entity/furniture/KnightStatue.java
- src/main/java/minicraft/entity/furniture/Lantern.java
- src/main/java/minicraft/entity/furniture/Spawner.java
- src/main/java/minicraft/item/FurnitureItem.java
- src/main/java/minicraft/level/Structure.java
Similar to #439 with same concept, but this is `Furnuture`.
> Renaming from Furniture#clone into Furniture#copy

- src/main/java/minicraft/core/Initializer.java
As this originally encounter weird FPS counting which makes the value shown always lower than the target value by 1, this "fixes" this counter and makes frame counting feel normal.
> Fix FPS counter

- src/client/java/minicraft/entity/furniture/Spawner.java
- src/client/java/minicraft/level/Level.java
> Modify spawner behavior

- src/client/java/minicraft/core/Updater.java
- src/client/java/minicraft/core/io/InputHandler.java
- src/client/java/minicraft/entity/mob/Player.java
- src/client/java/minicraft/screen/ContainerDisplay.java
- src/client/java/minicraft/screen/CraftingDisplay.java
- src/client/java/minicraft/screen/Display.java
- src/client/java/minicraft/screen/KeyInputDisplay.java
- src/client/java/minicraft/screen/Menu.java
- src/client/java/minicraft/screen/PlayerInvDisplay.java
- src/client/java/minicraft/screen/PopupDisplay.java
- src/client/java/minicraft/screen/QuestsDisplay.java
- src/client/java/minicraft/screen/ResourcePackDisplay.java
- src/client/java/minicraft/screen/TitleDisplay.java
- src/client/java/minicraft/screen/TutorialDisplayHandler.java
- src/client/java/minicraft/screen/WorldSelectDisplay.java
- src/client/java/minicraft/screen/entry/ArrayEntry.java
- src/client/java/minicraft/screen/entry/InputEntry.java
- src/client/java/minicraft/screen/entry/KeyInputEntry.java
This is a remake of both #515 and #533. This resolves the input key detecting problems in both modifiers and menu input transitions. An abstract class is added in this case, also ensuring safety for keys, without directly modifying the fields or states of the keys. No support for compounded inputs is removed.
For now, `+` is necessary for compounded inputs consisting of key mappings. The problems (related bugs) some menus and actions not detecting properly have been resolved.
> Improve key detection support in InputHandler

- README.md
> Change square braces to angular braces for dir in README

- README.md
Update information changed from POEditor to Lokalise.
> Update README.md about localization platform change

- src/client/java/minicraft/item/HeartItem.java
This is a missing piece for #439.
> Rename HeartItem#"clone" to "copy"
