- src/resources/localization/english_en-us.mcpl
- src/resources/localization/spanish_es.mcpl
so that there aren't so many "The string [blank] is not localized, returning itself instead."
> Updated localization files to be more recent

- src/minicraft/core/Renderer.java
- src/minicraft/core/io/Settings.java
Fps now defaults to monitor refresh rate instead of 60.
The arrow counter will only show while the player is holding something.
The black box ingame will only show while the player isn't creative or holding something. In any other mode it will show as normal.
> Ingame UI improvements + more.

- src/minicraft/gfx/Font.java
the Font.java file had a BOM, so, that's gone now
> Encoding stuff

- src/minicraft/core/io/Settings.java
The call to getDefaultScreenDevice() throws an exception if there is no screen (e.g. when starting a server in a headless environment).
Additionally the getRefreshRate() can return 0, which should be handled properly.
https://docs.oracle.com/javase/7/docs/api/java/awt/DisplayMode.html#getRefreshRate()
> Revert FPS setting

- src/main/java/minicraft/level/tile/InfiniteFallTile.java
The arrows, when a bow was used, could not pass the "InfiniteFall" tile, that is, the arrows were eliminated at the moment of touching said tile.
> Bug fix: arrows were not going through the infiniteFall tile

- src/main/java/minicraft/screen/entry/ListEntry.java
This is because of String#replaceAll uses regex, which it is asking
some regex pattern thereby now it's changed it to String#replace because
it doesn't use regex, avoiding this crash when typing characters like
"{", "[" or "("
This fixes related issue #218
> Fix that certain characters crash Inventory Search

- src/main/java/minicraft/screen/WorldSelectDisplay.java
When action is done either copy, rename or delete
this goes from World Select Display to World Edit
Display thereby that minicraft.core.Updater class
set the new parent to new menu that is World Edit
Display, but when it goes from World Edit Display
to World Select Display, minicraft.core.Updater
class initializes it with World Edit Display so
when user tries to exit from menu, it'll go back
again to previous World Edit Display. To avoid
this bug, World Select Display will select parent
correctly when editing process started if given
conditions are true that means that will pick
the select's parent from edit's parent what it'll
result as the initial parent
This fixes related issue #211
also I'm not sure if this might have another good fix for this bug but this is what it reaches first to …
> Fix parent when going back to World Select Display

- src/main/java/minicraft/core/Updater.java
- src/main/java/minicraft/level/Level.java
>  Dungeon chests will no longer appear too deep within obsidian walls.

- src/main/java/minicraft/core/Updater.java
- src/main/java/minicraft/core/io/InputHandler.java
- Inevntory Searcher bar shortcut was changed so that it does not interfere with the search
- Quick level change shortcut changed to not interfere with F3 without causing accidental level change
> Little changes

- src/main/java/minicraft/core/Initializer.java
Does anyone know why there was the 2 millisecond pause in the main game loop? I haven't experienced any issues from removing it and now the game runs perfectly at the fps cap.
> Fixed FPS not matching in-game cap

- src/main/java/minicraft/item/ToolType.java
- Increased durability 10 points
**Note**: If there are tools crafted and saved in worlds made before this change, those tools will lose 20-25% durability, when crafted again the durability will display correctly
> Increases tools durability

- src/main/java/minicraft/entity/mob/Player.java
This includes all the tile interaction (e.g. TreeTile, OreTile, RockTile, etc.).
Reason: The List of the entities of the tile includes particles. Particles need time to be disappeared; potential cooldown occurred.
Fixes #176
> Fix Interaction of active item

- src/main/java/minicraft/level/Level.java
- src/main/java/minicraft/screen/BookDisplay.java
- src/main/java/minicraft/screen/OptionsMainMenuDisplay.java
- src/main/java/minicraft/screen/PlayerInvDisplay.java
- src/main/java/minicraft/screen/ResourcePackDisplay.java
- src/main/java/minicraft/screen/SkinDisplay.java
- src/main/java/minicraft/screen/TitleDisplay.java
- Menus and some GUI components now adjust to aspect ratio
- Moved the Skins Entry to the Options Menu to reduce the amount of space taken up by the Title display options
- Fixed Resource packs and Skins menu, now its components are positioned correctly
- Fixed inventory search tip position
- Fixed Book gui height
- Fixed a bug regarding level rendering on screen
> Menus fixes for the aspect ratio

- src/main/java/minicraft/screen/PlayerInvDisplay.java
- src/main/java/minicraft/screen/WorldEditDisplay.java
- src/main/java/minicraft/screen/WorldGenDisplay.java
This fixes the world renaming from rendering wrong position when over 11 characters.
Also fixes the inventory key hint with weird positioning.
> Fix world rename rendering

- src/main/java/minicraft/entity/mob/Creeper.java
+ Added an explosion blacklist, now the creeper's explosion will no longer be able to break Hard rock, Obsidian walls or Raw obsidian tiles
> Fix Creepers explosions

- ChangeLog.txt
- src/main/java/minicraft/core/Initializer.java
- src/main/java/minicraft/core/io/FileHandler.java
- src/main/java/minicraft/screen/ResourcePackDisplay.java
- src/main/java/minicraft/screen/SkinDisplay.java
Right now, when the --savedir is specified the game appends "/.playminicraft/mods/Minicraft Plus" to it. However, this should not be the case. If the user gives a path to use as the save dir then that should be the final path to use.
> if --savedir is present, use it as final gameDir

- src/main/java/minicraft/core/Initializer.java
- src/main/java/minicraft/core/Renderer.java
As the title described, this adds a logo splash screen other than the jar splash screen. It is because there are still moments the main game renderer has not started.
> Add Logo Splash Screen before first render

- src/main/java/minicraft/level/Level.java
- Lanterns, specifically the gold one, have a larger light radius than the radius the game is able to render once the source object is off screen rendering.
- This should fix #253
> Fix lighting rendering

- src/main/java/minicraft/item/FishingData.java
- When they made changes to the game's resource directory, they forgot to also update the path where the fishing system loot is obtained, causing the game to crash when trying to fish something
> Fix fishing data wrong path

- src/main/java/minicraft/entity/mob/Cow.java
- src/main/java/minicraft/entity/mob/Sheep.java
Resolves #225
Sheep and cow now eat grass on the floor. (grazing)
Tile interaction is added instead of interacting with item entities because making passive mobs eating dropped food items on the ground does not make sense. First, the item entities disappear in very short time. Second, items are dropped *only when the player drops items manually*, so, the chance of making this happening is too small. Third, meeting passive mobs is already a rare thing. These factors are the points needed to be considered into account.
> Making sheep and cow eating grasses

- src/main/java/minicraft/screen/CraftingDisplay.java
- src/main/java/minicraft/screen/PopupDisplay.java
- src/main/java/minicraft/screen/WorldGenDisplay.java
Resolves a `NullPointerException` in `CraftingDisplay#render` method.
The `OnScreenKeyboardMenu` objects are now rendered on `PopupDisplay` and `WorldGenDisplay`.
> Resolve problems about the OSK Menu

- src/main/java/minicraft/core/io/FileHandler.java
- src/main/java/minicraft/screen/ResourcePackDisplay.java
As I test once more, it is found that the problem is not completely resolved. The problem in `FileHandler#listAssets()` is resolved by #421 previously, but the OS-dependent separator problem (zip files must use `/` as the separator but Windows uses `\` as the separator) and directory name conversion problem (directory paths do not directly convert into `String` with a tailing slash, and thus the path name is not recognized as a directory in zip file, which making unexpected files generated in temp zip files) exist. This fixes these problems and makes sure that `gradle run` can work properly.
> Further resolves gradle run problem

- src/main/java/minicraft/entity/mob/Player.java
Fixes weird rendering when falling on water. Originally falling on water renders rotating on water instantly. Also, falling now always renders "carrying" sprites.
> Fix wrong rendering falling on water

- src/main/java/minicraft/level/Level.java
- Removes the redundant `Level#sparks` set for sparks as there are no difference if they are combined into `Level#entities` set.
- Fixes the potential problem about y-axis (part of coordinate setting) is not looped due to the always-false conditional expression in some furniture generation.
- Makes `#toArray()` function always use empty arrays.
> Clean up Level.java

- src/main/java/minicraft/saveload/Load.java
- src/main/resources/resources/data/chestloot/dungeonchest.txt
- src/main/resources/resources/data/chestloot/minidungeon.txt
As #423 replaced `Potion` item by `Awkward Potion`, there are unchecked problems that `Potion` items in old world are still being loaded without resolving them into `Awkward Potion` and thus resolving into instances of `UnknownItem`. Also, the chestloot tables are still using "potion" instead of "awkward potion", leading to the similar problem.
> Fixes unknown item "Potion" unresolved

- src/main/java/minicraft/saveload/Load.java
This problem is led by #403, containing unchecked problem that some of world loading versioning checks have used 2.2.0-dev2, which have already been released earlier. This is because the code was originally planned for dev2 but not for dev3. This may not be happening again due to confirmation of public release quality. Loading old world of a previous version should be checked as valid before releasing.
For players playing 2.2.0-dev3 and attempting to load old world of 2.2.0-dev2, two valid corresponding solutions in *solving* this problem are:
- The most problem-solving solution is modifying the world version saved in `Game.miniplussave`, into 2.2.0-dev1. This could let the game know that the world is old enough and there would not be further more problem in loading them as no more …
> Fixes loading bugs by obsidian knight update

- src/main/java/minicraft/item/SummonItem.java
As Obsidian Knight can only be summoned at the center of the boss room, the condition is updated. It should now be able to summon Obsidian Knight anywhere in the boss room.
> Obsidian Knight summon update

- src/main/java/minicraft/core/io/Settings.java
After the change with FPS entry, the default value is always the first element, i.e. 10, which is not expected as a general default value. The default value is now determined by default monitor refresh rate. If the refresh rate is not a multiple of 10, it is subtracted until it is a multiple of 10. If the rate cannot be identified, 60 is used.
> Default FPS value

- src/main/java/minicraft/entity/mob/Player.java
This fixes a bug that when a player is fishing and drop the item, open inventory menu or pick up a furniture, an error occurs. This is because the fishing state clean is done only when attacking again or the player is sleeping or swimming, but not for returning the item back to inventory and thus leading a `NullPointerException` for `activeItem` in rendering with `isFishing`.
> Fix a crash returning item when fishing

- src/main/java/minicraft/core/Renderer.java
- src/main/java/minicraft/core/io/Settings.java
It fixes the canvas initialization issues on Unix-like platforms. Works for me, on linux and should also work for [issue #465](https://github.com/MinicraftPlus/minicraft-plus-revived/issues/465).
> Fixed buffering problem on linux and os x

- src/main/java/minicraft/entity/FireSpark.java
Originally, fire sparks pass through walls. but it seems that it would affect the feature of the boss room. The use of the boss room is to block all activities withinn the room interacting outside. Fire sparks also despawn after 50 ticks stopped by walls to prevent duplication and this may lightly increase the difficulty of the boss.
> Fire sparks now collide with walls and disappear after a period stopped by walls

- src/main/java/minicraft/core/io/Settings.java
https://github.com/MinicraftPlus/minicraft-plus-revived/commit/9de1e2a200cec588d80e21d9a2bd4b3df976104d reverted an unrelated change apart from the FPS setting change, which is the language setting entry, which had already been replaced by a separated display before.
> Removes redundant lines by the revert

- src/main/java/minicraft/screen/LoadingDisplay.java
This problem causing dungeon regeneration blocking an AWT thread is caused by a commit https://github.com/MinicraftPlus/minicraft-plus-revived/commit/053a4d940bde8d7bc4a64a52cf212646de882feb. This is done by mistake, so this adds back the thread use as this blocks the thread even in a timer thread.
When exiting the regeneration, it originally exits 3 times, but it is expected to exit only twice. This problem is resolved.
There is a problem with the parent display resolving which causes the loading display initializing the second time when exiting the regeneration causing undefined behaviour. The temporary resolution is to stop initializing the second time within the loading display.
> Resolve dungeon regeneration blocking problem

- src/client/java/minicraft/core/Game.java
- src/client/java/minicraft/core/Initializer.java
- src/client/java/minicraft/core/Renderer.java
After #495, the logo splash screen is completely removed by the request by @Makkkkus. Also, the window is now launched when canvas is ready to render. In a most ideal case, the window should be launched once the first render has been made.
> Remove logo splash screen

- src/client/java/minicraft/core/Initializer.java
- src/client/java/minicraft/core/io/InputHandler.java
In my test with VisualVM profiler, it is unknown that the while loop processing without `Updater#tick()` or `Renderer#render()` invokes occupying relatively great amount of CPU time in self-time. According to my computer, this reduces averagely around 60%-70% of CPU usage in title screen and 50% in a just created world. A thread blocking/sleeping is always needed to prevent while loop looping with empty body using indefinite amount of CPU time. This also presents in the original Minicraft `Game#run()` code (with `Thread#sleep(2)`). `1.01` in the FPS time check is used for relax the hard FPS restriction to prevent from running down the maximum value.
Reference: https://stackoverflow.com/a/61598906
> Optimize CPU usage

- src/client/java/minicraft/saveload/Load.java
In the current `Load#loadPrefsOld`, skin index is missing and the order of language settings is not correct. Also, after my deep search, I have found that language setting is not 2.0.3-dev1, instead, the setting is valid since 2.0.4-dev3.
If my prediction is correct, loading preferences with versions 2.0.3-dev1 to 2.0.4-dev2 would throw exception `IndexOutOfBoundsException: Index 0 out of bounds for length 0`, and with versions after 2.0.4-dev2 (dev3 and later), language preference would not be loaded and for multiplayer preferences: saved IP would be saved UUID; saved UUID would be saved username; saved username would be old language preference. Or, with versions after 2.0.4-dev2, exception `ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1` might be thrown.
> Fix loadPrefsOld

- src/client/java/minicraft/screen/SkinDisplay.java
This reverts a change by da6d4799577222c3ad12007c7005c454a382f6ef in #413. In fact, the first line (0, 0, 64, 16) contains normal skins and the second line (0, 16, 64, 16) contains furniture holding skins, so this is a mistake of determining this as redundant. The current sheet does not include the second line, so this leads to a texture missing in furniture holding rendering.
> Fix furniture holding player sprites missing

- src/client/java/minicraft/screen/entry/ArrayEntry.java
This is similar to #514, but instead, when pressing Alt and modifying a range entry, the value changes by 10 instead of 1 in selection.
> Add an ability to fast scroll RangeEntry

- src/client/java/minicraft/screen/ContainerDisplay.java
* The order of the inventories menus was changed, now the player's inventory will be on the left, and the chest inventory will be on the right
- This should fix #537
> Move chest menu to the right

- src/client/java/minicraft/item/ClothingItem.java
- src/client/java/minicraft/item/PotionItem.java
As described, as these two items should not return item in creative mode, they now do not return empty glass bottle and previous clothing item when used in creative mode.
> Make PotionItem and ClothingItem not return consumed item when used in creative mode

- src/client/java/minicraft/entity/mob/Player.java
Similar to #462, but this patches the missing parts that are related to `Item#isDeleted()` checks. The resultant crashes are the same.
> Add missing fishing interrupt handles

- src/client/java/minicraft/entity/mob/ObsidianKnight.java
- src/client/java/minicraft/item/SummonItem.java
- src/client/resources/assets/localization/en-us.json
As the number of Knight Statue is unlimited, there can be many Knight Statues placed on the same destination tile. Unintended behaviours might be allowed to happen.
This also includes a fix for Obsidian Knight phase sprite problem.
> Add Knight Statue limit and fix Obsidian Knight phase problem

- src/client/java/minicraft/saveload/Load.java
This would fix #564.
This is a further fix for #519. As the preferences may contain empty values, if the preferences contain empty values, unexpected errors may occur due to the original design based on values "as is" (without empty string removals).
Bypassing this problem in 2.2.0-dev3, users can first launch versions before 2.2.0-dev3 to generate JSON format preferences without this kind of error (as mentioned in https://github.com/MinicraftPlus/minicraft-plus-revived/pull/519#issuecomment-1694990750).
Note that if players have already been using 2.2.0-dev3 or 2.2.0-dev2 updating their preferences, the preferences settings might have already been broken.
> Remove the removal for empty values in saves

- src/client/java/minicraft/entity/mob/Mob.java
- src/client/java/minicraft/entity/mob/MobAi.java
- src/client/java/minicraft/level/Level.java
This fixes that mobs cannot be normally spawned because of the misconfigurations. The main reason is that the values are set as the tile distances for entity despawn distances. A use of using `Math#hypot` is prevented to speed up the calculation.
> Fix mobs spawning

- src/client/java/minicraft/core/Updater.java
This problem causes some displays not working properly depending on `Display#onExit()` invokes. This involves changes by #436 that the display handler is using a `ArrayDeque` and loops.
> Fix a problem on missing Display#onExit

- src/client/java/minicraft/level/Level.java
As spotted out by @Litorom, there is an exception regarding the enemy level.
```
Unhandled error: General Application Crash
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
at minicraft.entity.mob.EnemyMob.render(EnemyMob.java:106)
at minicraft.level.Level.sortAndRender(Level.java:536)
at minicraft.level.Level.renderSprites(Level.java:499)
at minicraft.core.Renderer.renderLevel(Renderer.java:209)
at minicraft.core.Renderer.render(Renderer.java:119)
at minicraft.core.Initializer.run(Initializer.java:100)
at minicraft.core.Game.main(Game.java:116)
```occurred in the dungeon level.
This is related to the wrong code getting the level. In the current code, the depth number is mapped to level index ranged from 0 to the number of levels-1, but the enemy level only …
> Fix wrong enemy level in mob generation

- src/client/java/minicraft/entity/Entity.java
- src/client/java/minicraft/entity/Spark.java
- src/client/java/minicraft/entity/mob/ObsidianKnight.java
Resolves #602
A `NullPointerException` would be thrown as there are missing null handles.
This kind of potential bugs would be reduced by the time #512 is finished.
Known ways to reproduce:
- Player dies when there is a spark exists (can be generated by AirWizard) (? to 2.2.0-dev4)
- Player dies when Obsidian Knight is active. (Unchecked) (2.2.0-dev3 to 2.2.0-dev4)
> Resolve any potential NullPointerException throws caused by Entity#getClosestPlayer()

- src/client/java/minicraft/entity/mob/MobAi.java
- src/client/java/minicraft/level/Level.java
As for larger worlds, the game lags. This update the codes that uses the entire level for light radius check while it is not necessary. Please note that if modders have new light sources, they need to handle them themselves. Therefore, for `2.2.0-dev4` worlds larger than 128, the game is very lag.
> Reduce light radius check for mob despawning

- src/client/java/minicraft/entity/furniture/Tnt.java
_This bug seems to have been present for too long_
- Previously, when a player tried to pick up the placed Tnt to put it in their inventory, they could not do so and it would activate and explode accidentally, this because we did not handle that case within the appropriate method
- The player can now collect TNT again as long as it has not been previously activated
> Fixed Tnt interaction

- .github/workflows/autobuild.yml
Now this workflow should now be able to run only when there is no successful or running auto build job since the latest commit not committed by Actions. This runs every time a pull request closed, manually or every 4 hours. A check is done before running. Within the check, it first fetches the commit datetime of the latest commit not committed by Actions (number of items: 30); then it searches for the presence of any successful or running or pending workflow runs (number of items: 30); it sends the boolean value to the environment about to continue the job or not, it is true if the presence is false; if the sent value is false, it aborts (cancels the workflow run). The build job requires conditions to run first, so that it will run only when conditions are successful.
> Rate limit for autobuild.yml

- src/client/java/minicraft/entity/Entity.java
In Entity::moveByEntityHitBoxChecks, when calling the bumpingHandler and steppingHandler the horTile and frontTile were switched. This fixes sand particles spawning in the wrong tiles.
> Fix steppedOn and bumpedOn x and y positions

- src/client/java/minicraft/core/io/FileHandler.java
This resolves `NoSuchFileException` that occurs when moving old data folder contents to the new destination. This is because copying does not create new directory.
> Handle old folder copying destination file not having folder

- src/client/java/minicraft/item/BookItem.java
A `NullPointerException` occurred when interacted because the book content of the default book item has been set to `null`. The change was made by the resource pack update but later not updated correspondingly. This fixes this issue and set the book content back to the default empty one.
> Fix book item NullPointerException

- src/client/java/minicraft/item/Recipes.java
There is a view that both iron and gold are quite expensive if it costs 4 ores, so they are tweaked down to 3 ores.
> Tweak iron and gold recipe cost down to 3 ores

- src/client/resources/resources/recipes.json
Right now, players do not have access to the correct iron and gold bar recipes in the furnace. Updated "resources/recipes.json" to reflect new furnace recipes.
> Fixed unlocked iron and gold recipes not matching actual recipe

- src/client/java/minicraft/saveload/Load.java
This changes in addition to #640, that the old recipes for 4 ores are being skipped in world loading so that they will no longer be saved in the list of unlocked recipes. This is for the forward compatibility. Players will obtain the new recipes for both iron and gold, then there should be no further problem with the shift of recipe changes.
> Skip changed iron and gold recipes in world loading

- CODE_OF_CONDUCT.md
- SECURITY.md
As part of [GitHub Community Standards](https://github.com/MinicraftPlus/minicraft-plus-revived/community)
For the Code of Conduct, it is mostly the same as the one in the list of templates except the changes under the section of "Enforcement".
Contributing guidelines will be done later until we have more definite rules and standards set.
> Complement GitHub Community Standards

- src/client/java/minicraft/level/tile/GrassTile.java
- src/client/java/minicraft/level/tile/SandTile.java
Resolves #700.
This restriction exists for both `GrassTile` and `SandTile`.
Related investigation to the effect is done previously:
> The effects when there are tiles exist on orthogonal directions (for each pair of orthogonal directions):
> ```mermaid
> flowchart LR
>     A1[corner] --> B11[diagonal]
>     A1 --> B12[!diagonal]
>     A2[!corner] --> B21[diagonal]
>     A2 --> B22[!diagonal]
>     B11 --> single
>     B21 --> single
>     B12 --> corner
>     B22 --> full
>     B12 -.-> B11
>     B22 -.-> B21
> ```
> > single: singleton texture with connective; takes place only on corner parts; using "full" over "border center"
> > corner: whether corner texture is set
> > diagonal: whether diagonal tile exists
> > *dotted arrow*: effect of `!side` code
Source: …
> Remove redundant hardcoded code to tile corner rendering

- src/client/java/minicraft/entity/Entity.java
- src/client/java/minicraft/entity/FireSpark.java
Main issue fixed:
`Entity#move` still returned `true` even when not moved as either x or y delta is zero. The boolean result should indicate whether the entity *is moved* (`false` whenever completely not moved), when any non-zero argument is passed. (This issue was found when doing #592)
Furthermore, the line
```java
if (d == 0) return true; // Was not stopped
```
was kept just because the original method contains the check, but was for when *both x and y delta are zero*. The code is then checked somehow to be logically incorrect, and the actual logically correct line already exists in `#move` as
```java
if (Updater.saving || (xd == 0 && yd == 0)) return true; // Pretend that it kept moving
```
Minor (potential) issues in `FireSpark` (mostly fixed):
- `Entity#x` and `Entity#y` used in …
> Fix issues regarding entity movement methods

- src/client/java/minicraft/screen/PlayerInvDisplay.java
Fixes #703
This greatly demonstrated an example of what could happen when low level programming bugged in high level language. If it is C/C++, just undefined bahaviour instead of an exception or error.
This should be a bug since 2.2.0-dev1 (29f6ff86ffaeaf98c669b269800b133997c445a3). I believe it was because the code was copied directly from `ContainerDisplay` without further examination and modification. It should be a `ArrayIndexOutOfBoundsException` but since 2.2.0-dev4 (33c50838153e0e758845f64148e01da055faa70b), a description menu has been added, so the 1st menu become the description menu when not in creative mode and thus not the requested `InventoryMenu` (`ClassCastException`), causing the exception.
The part of code is executed when a stack of item is updated when in menu or …
> Fix unconstrained code for PlayerInvDisplay menu updating

- src/client/java/minicraft/core/io/FileHandler.java
- src/client/java/minicraft/screen/ResourcePackDisplay.java
Instead of creating a random temp file with the jar resources it now just loads it as if it was a directory. That also means that now folder resource packs are supported.
> Remove unnecessary rp temp

- src/client/java/minicraft/screen/PlayerDeathDisplay.java
This fix addresses an exploit in Hardcore mode where, upon death, a player could continue playing in the same world. If the player manually saved the world before dying, they could simply choose the "Quit" option from the death menu to return to the main menu without saving, and then reload the world
> Fixed Hardcore Death Menu Exploit
